# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.62.1"

default_platform :ios

platform :ios do
  before_all do
  end

  def run_localizer
    sh "cd .. && sh scripts/localizer.sh Trust " << ENV['LOKALISE_API_TOKEN']
  end

  def screenshots
    snapshot
    frameit(white: true)
  end
  
  lane :refresh_dsyms do
    download_dsyms                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    cocoapods(use_bundle_exec: false)
    increment_build_number
    ensure_git_branch()
    increment_version_number(bump_type: "minor")
    cert
    match(type: "appstore", readonly: true)
    gym(scheme: "Trust")
    commit_version_bump(message: "Version Bump", force: true)
    deliver(force: true)
    upload_symbols_to_crashlytics(dsym_path: "Trust.app.dSYM.zip")
    push_to_git_remote
  end

  desc "Screenshots"
  lane :screenshots do
    screenshots
  end

  desc "Localize"
  lane :localize do
    run_localizer
  end

  lane :update_lokalise do
    lokalise_metadata(
      api_token: ENV['LOKALISE_API_TOKEN'],
      project_identifier: ENV['LOKALISE_STORE_PROJECT_ID'],
      action: "update_lokalise",
      add_languages: true,
      override_translation: false
    )
  end

  lane :update_itunes do
   lokalise_metadata(
      api_token: ENV['LOKALISE_API_TOKEN'],
      project_identifier: ENV['LOKALISE_STORE_PROJECT_ID'],
      action: "update_itunes"
   )
  end

  lane :tests do 
    cocoapods(use_bundle_exec: false)
    run_tests(
      workspace: "Trust.xcworkspace",
      scheme: "TrustTests",
      clean: false
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
