# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  #{}"iPhone 7",
  "iPhone 7 Plus",
  "iPhone X",
  #{}"iPhone 5",
  "iPad Pro (12.9-inch)",
  #{}"iPad Pro (9.7-inch)",
  #{}"Apple TV 1080p"
])

languages([
  "en-US",
  #{}"de-DE",
  #{}"it-IT",
  #["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
scheme "TrustUITests"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

configuration "Debug"
# clean true

skip_open_summary false
ios_version '11.0.1'

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
